# Generated by Django 3.2.8 on 2021-11-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylandlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='management_company',
            field=models.CharField(max_length=30),
        ),
    ]
